CREATE DATABASE AirbnbMicroDB;
USE AirbnbMicroDB;
CREATE TABLE airbnb_microeconomic_data(
    id BIGINT PRIMARY KEY,
    host_id BIGINT,
    host_is_superhost VARCHAR(10),
    host_identity_verified VARCHAR(10),
    calculated_host_listings_count INT,
    neighbourhood_cleansed VARCHAR(150),
    latitude DECIMAL(10, 7),
    longitude DECIMAL(10, 7),
    room_type VARCHAR(50),
    accommodates INT,
    bedrooms FLOAT,
    beds FLOAT,
    minimum_nights INT,
    maximum_nights INT,
    availability_30 INT,
    availability_365 INT,
    number_of_reviews INT,
    last_review VARCHAR(50),
    reviews_per_month DECIMAL(5,2),
    review_scores_rating DECIMAL(5, 2),
    review_scores_cleanliness DECIMAL(5,2),
    review_scores_location DECIMAL(5,2),
    city VARCHAR(50),
    original_currency VARCHAR(10),
    price_euro DECIMAL(10, 2),
    has_wifi VARCHAR(10),
    has_workspace VARCHAR(10),
    has_aircon VARCHAR(10),
    has_kitchen VARCHAR(10),
    has_free_parking VARCHAR(10),
    has_luggage_dropoff VARCHAR(10),
    has_elevator VARCHAR(10),
    has_self_check_in VARCHAR(10),
    has_refrigerator VARCHAR(10),
    has_washer VARCHAR(10),
    has_dryer VARCHAR(10),
    has_balcony VARCHAR(10),
    has_pool VARCHAR(10),
    has_hottub VARCHAR(10),
    amenities_count INT,
    property_category VARCHAR(50)
);
